services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesappdb
      MYSQL_USER: springnotesuser
      MYSQL_PASSWORD: 12345
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u "springnotesuser" --password=12345
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - "3306:3306"
  spring-app:
    build:
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notesappdb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: springnotesuser
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      mysql:
        condition: service_healthy
  react-app:
    build:
      context: ../react-app
      dockerfile: dockerfile
    ports:
      - "3000:80"